<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="3" total="7" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="88" started-at="2021-12-09T14:21:13 IST" finished-at="2021-12-09T14:21:13 IST">
    <groups>
      <group name="Add">
        <method signature="Test1.testcase1()[pri:0, instance:com.groupsConcepts.Test1@520a3426]" name="testcase1" class="com.groupsConcepts.Test1"/>
        <method signature="Test2.testcase5()[pri:0, instance:com.groupsConcepts.Test2@6536e911]" name="testcase5" class="com.groupsConcepts.Test2"/>
        <method signature="Test2.testcase6()[pri:0, instance:com.groupsConcepts.Test2@6536e911]" name="testcase6" class="com.groupsConcepts.Test2"/>
        <method signature="Test2.testcase7()[pri:0, instance:com.groupsConcepts.Test2@6536e911]" name="testcase7" class="com.groupsConcepts.Test2"/>
      </group> <!-- Add -->
      <group name="Tag">
        <method signature="Test2.testcase7()[pri:0, instance:com.groupsConcepts.Test2@6536e911]" name="testcase7" class="com.groupsConcepts.Test2"/>
      </group> <!-- Tag -->
    </groups>
    <test name="Test" duration-ms="88" started-at="2021-12-09T14:21:13 IST" finished-at="2021-12-09T14:21:13 IST">
      <class name="com.groupsConcepts.Test1">
        <test-method status="FAIL" signature="testcase1()[pri:0, instance:com.groupsConcepts.Test1@520a3426]" name="testcase1" duration-ms="6" started-at="2021-12-09T14:21:13 IST" finished-at="2021-12-09T14:21:13 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.groupsConcepts.Test1.testcase1(Test1.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- com.groupsConcepts.Test1 -->
      <class name="com.groupsConcepts.Test2">
        <test-method status="PASS" signature="testcase5()[pri:0, instance:com.groupsConcepts.Test2@6536e911]" name="testcase5" duration-ms="10" started-at="2021-12-09T14:21:13 IST" finished-at="2021-12-09T14:21:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase5 -->
        <test-method status="PASS" signature="testcase6()[pri:0, instance:com.groupsConcepts.Test2@6536e911]" name="testcase6" duration-ms="2" started-at="2021-12-09T14:21:13 IST" finished-at="2021-12-09T14:21:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase6 -->
        <test-method status="PASS" signature="testcase7()[pri:0, instance:com.groupsConcepts.Test2@6536e911]" name="testcase7" duration-ms="4" started-at="2021-12-09T14:21:13 IST" finished-at="2021-12-09T14:21:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase7 -->
      </class> <!-- com.groupsConcepts.Test2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
